timer_main:
  rate: 5.0 # [Hz]

tracker: "MpcTracker"
controller: "Se3Controller"
constraints: "slow"
altitude_estimator: "height"

min_distance_before_landing: 15.0 # [m]

service_n_attempts: 30
service_repeat_delay: 0.1
